version: '2'
services:
  build:
    image: jetbrainsinfra/golang:1.11.3
    volumes:
      - .:/work
      - modules:/go/pkg/mod
      - cache:/cache
    working_dir: /work
    environment:
      GOCACHE: /cache
    command: ./build.sh

  test:
    image: jetbrainsinfra/golang:1.11.3
    volumes:
      - .:/work
      - modules:/go/pkg/mod
      - cache:/cache
    working_dir: /work
#    network_mode: "container:vpn"
    environment:
      GOCACHE: /cache
      VSPHERE_USERNAME:
      VSPHERE_PASSWORD:
    command: ./test.sh

volumes:
  modules:
  cache:
