version: '2'
services:
  build:
    image: jetbrainsinfra/golang:1.11.3
    volumes:
      - .:/work
    working_dir: /work
    command: ./build.sh

  test:
    image: jetbrainsinfra/golang:1.11.3
    volumes:
      - .:/work
    working_dir: /work
#    network_mode: "container:vpn"
    environment:
      - VSPHERE_USERNAME
      - VSPHERE_PASSWORD
    command: ./test.sh
