[[constraint]]
  name = "github.com/hashicorp/packer"
  version = "~1.3"

[[constraint]]
  name = "github.com/vmware/govmomi"
  version = "~0.19"

[[override]]
  name = "github.com/masterzen/azure-sdk-for-go"
  branch = "master"

# need commit https://github.com/ChrisTrenkamp/goxpath/commit/e2e5bcefc4e07f4a0c587a1200c22665dd39bd0e
[[override]]
  name = "github.com/ChrisTrenkamp/goxpath"
  branch = "master"

# Plugin's RPC client uses the same version of a codec as a server in Packer core
[[override]]
  name = "github.com/ugorji/go"
  revision = "646ae4a518c1c3be0739df898118d9bccf993858"

[prune]
  go-tests = true
  unused-packages = true
